spring:
  datasource:
    password: 123456
    url: jdbc:postgresql://localhost:5432/deharri-user-mgmt-db
    username: haris

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:default}
    password: ${MAIL_PASSWORD:default}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    transport:
      protocol: smtp


  data:
    jdbc:
      dialect: postgresql

  jpa:
    hibernate:
      ddl-auto: create-drop
  kafka:
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8081
  forward-headers-strategy: framework  # Important for proxied requests

logging:
  level:
    org.apache.kafka: ERROR

app:
  cors:
    allowed-origins:
      - http://localhost:8081

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    config-url: /ums/v3/api-docs/swagger-config
    url: /ums/v3/api-docs


jwt:
  secret: hMbhMVBaYZDAM4pNeTZ0uNt4M9e/Zv5io+tqukPce9Q=

aws:
  accessKeyId: AKIA3Z2SS7HTNR6E5OMQ
  secretKey: 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
  region: us-east-1
  s3:
    bucket: deharri-bucket

