spring:
  application:
    name: user-mgmt-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:postgres}:${DB_PORT:5432}/${DB_NAME:deharri-user-mgmt-db}
    username: ${DB_USER:haris}
    password: ${DB_PASSWORD:123456}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:default}
    password: ${MAIL_PASSWORD:default}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    transport:
      protocol: smtp

  data:
    jdbc:
      dialect: postgresql

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081
  forward-headers-strategy: framework

logging:
  level:
    root: INFO
    org.apache.kafka: ERROR
    com.deharri.ums: INFO

app:
  cors:
    allowed-origins:
      - http://localhost:8081
      - http://localhost:5173
      - http://localhost:5174
      - http://localhost:3000

jwt:
  secret: ${JWT_SECRET:hMbhMVBaYZDAM4pNeTZ0uNt4M9e/Zv5io+tqukPce9Q=}

aws:
  accessKeyId: ${AWS_ACCESS_KEY_ID:}
  secretKey: ${AWS_SECRET_ACCESS_KEY:}
  region: ${AWS_REGION:us-east-1}
  s3:
    bucket: deharri-bucket

# Enable Eureka client in Docker/Dev mode
eureka:
  client:
    enabled: true
    service-url:
      defaultZone: ${EUREKA_URI:http://eureka:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /ums/v3/api-docs
        name: User Management Service API
    config-url: /ums/v3/api-docs/swagger-config
    # Add these for gateway support
    use-root-path: false
    operations-sorter: method
    display-request-duration: true
    tags-sorter: alpha
    disable-swagger-default-url: true
    # Important: Add X-Forwarded-Prefix handling
    url-prefix: /ums

