spring:
  profiles:
    active: local

  datasource:
    password: ${DB_PASSWORD:123456}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:deharri-user-mgmt-db}
    username: ${DB_USER:haris}